# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 426385feb2caa366a6d4bb91a224baa6bc724f0f95ed645e932e24523e118d66bdbcb1a30532c42ddd18ca9640390baeadeaac445b54144af45672debb786242

test:
  secret_key_base: 0243ec401fb6bcb5d0f588694cde769c250ea873a672ef1f5af44cb6fe05a789ffdb3328f4cf062b523da675010979eb7dd6f2f20f05570466a88b7e7a0c5f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
